### ISSUE TITLE
Add search functions

### ISSUE THREAD

**Issue by danverde** [byuitechops/d2l-to-canvas-conversion-tool#20]
For pre-import only

We need:
1. Search by filename - returns array of files with given string in their name
2. Search for file by name - returns a single file with the exact name given
3. Search by extension - returns array of files with the given extension (uses file.ext property)
4. Search by CSS selector - use node cheerio package
5. Search by XML CSS selector - also cheerio

**Comment by zlw11063** [comment]
All are done except 4 and 5

**Comment by zlw11063** [comment]
Do we want to build these into the course object? Cheerio is useful for more than finding things by CSS selector, so we may want them to just require it on their child module instead of using the course object to work with it.

**Comment by zlw11063** [comment]
We decided to just let the authors of child modules write these on their own, since each one might be a little different. A single search function would be too general, and the effort to write search modules to encompass as many situations as possible would be just as much effort as writing on their own.

Example: The course selector search function finds all files based on a CSS selector provided. That may return both XML and HTML files, but the user only wants the XML files. The search function would probably be a filter(). The user would have to do a second filter() to get just the XML files from the response of the search function. Easier to have the author just do both in a single filter function.
